# Generated by Django 3.1.1 on 2020-09-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0002_auto_20200913_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='created',
        ),
    ]
